language: php
php:
  - "5.6"
  - "7.0"

install:
  - composer install
  - composer dumpautoload

before_script:
  - curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.12.4/php-cs-fixer.phar -o php-cs-fixer

script:
  - php-cs-fixer fix -v --dry-run --level=psr2 src
